[package]
name = "data_pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
pariter = "0.5.1"
polars = { version= "0.32.1", features = ["lazy", "parquet","concat_str"] }
